export const CATEGORY_ACTION_TYPES ={
    SET_CATEGORY_MAP_START:'SET_CATEGORY_MAP_START',
    SET_CATEGORY_MAP_SUCCESS:'SET_CATEGORY_MAP_SUCCESS',
    SET_CATEGORY_MAP_ERROR:'SET_CATEGORY_MAP_ERROR'
   
}